### ISSUE TITLE
Implement tracefile runner as test level 3

### ISSUE THREAD

**Issue by ClemensLinnhoff** [openMSL/sl-1-3-object-based-generic-perception-object-model#10]
**Is your feature request related to a problem? Please describe.**
In [test level 3](https://github.com/openMSL/sl-1-5-sensor-model-testing/blob/main/doc/test_architecture.md#3-run) the model shall be checked for runtime errors. This needs to be implemented

**Describe the solution you'd like**
Implement a trace file player and connect it to the model fmu via a co-simulation platform (e.g. [OpenMCx](https://github.com/eclipse/openmcx)). That way, the model can be checked for runtime errors and at the same time, the model output can be evaluated.

**Comment by jdsika** [comment]
I have the issue that I want to look at the .ssd architecture but I can only upload .ssp files and not .ssd. What can we do about it?

**Comment by ClemensLinnhoff** [comment]
You mean in easy-ssp?
An .ssp file is just a zip containing the .ssd (among other stuff). Unfortunately I tried packaging it into an ssp zip, put easy-ssp throws an error message, when I try to upload it. I think this has something to do with the paths of the fmu. Usually all the fmus are in a resources folder within the ssp archive. But as we copy them from different places in the pipeline, they are placed in the tmp folder. I think easy-ssp has a problem with that.
Because I have a defacto identical ssd file where just the paths of the fmus are different and that one works with easy-ssp.

**Comment by ClemensLinnhoff** [comment]
If it is a requirement, that everything is packaged into an ssp file, we could copy the built FMUs to the right place and then create the ssp archive and output it as an Action artifact. However, this might work in this simple example (although the path of the trace file also has to be set) but when testing becomes more complex, e.g. with a scenario catalog, I am not sure if we can put everything into an ssp archive with all the dependencies.

**Comment by jdsika** [comment]
No, I think the requirement goes towards Easy-SSP to allow for URLs as FMU paths including git repos. @wiesmayer

Is it allowed according to the SSP specification?

**Comment by wiesmayer** [comment]
Jes @jdsika it is allowed from the SSP spec, but not in our tool easySSP yet - I will add it to our requested features list
