### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by Vinarpith** [openMSL/sl-1-3-object-based-generic-perception-object-model#25]
Hello Team, 
I am CarMaker user and trying to install this setup in my windows machine, installed cmake, and I am using Visual Studio Code, installed Prodbuf, but I am not sure about installation, can you please guide me in installation and running a scenario from CarMaker please?

**Comment by ClemensLinnhoff** [comment]
Is this still a problem @Vinarpith? Otherwise I would close this issue.

**Comment by ClemensLinnhoff** [comment]
Closing issue as stale.
