### ISSUE TITLE
Need Support on FMU_INSTALL_DIR creation

### ISSUE THREAD

**Issue by Vinarpith** [openMSL/sl-1-3-object-based-generic-perception-object-model#26]
I've completed Install [cmake](https://github.com/Kitware/CMake/releases/download/v3.20.3/cmake-3.20.3-windows-x86_64.msi)
I've completed Install protobuf for [MSYS-2020](https://github.com/openMSL/sl-1-3-object-based-generic-perception-object-model/blob/main/doc/build-instructions/install_protobuf_Win64_MSYS-2020.md)
Now I need support on installing **FMU_INSTALL_DIR**

**Comment by ClemensLinnhoff** [comment]
Is this still a problem @Vinarpith? Otherwise I would close this issue.
