### ISSUE TITLE
Unexpected Output from FMU Sensor

### ISSUE THREAD

**Issue by levanthanh3005** [openMSL/sl-1-3-object-based-generic-perception-object-model#30]
Hi @ClemensLinnhoff 
I tried to simulate the perception object model with the required inputs,
I checked the logs and saw that it already runs steps: frontend => data extraction => object tracking
I also configure the CSV results as 

DetectedObjects:
![image](https://github.com/openMSL/sl-1-3-object-based-generic-perception-object-model/assets/7145124/3a70ea3e-ceb6-4ec7-87ca-8939ee32f074)
 
GTObjects:
![image](https://github.com/openMSL/sl-1-3-object-based-generic-perception-object-model/assets/7145124/76f5d9c8-f359-4616-a6f6-6bc59b87a451)

However when I convert the data from the output of FMU, it almost contains nothing,
![image](https://github.com/openMSL/sl-1-3-object-based-generic-perception-object-model/assets/7145124/697736b3-5d29-40db-a4c4-ffd8b3164548)

I used the carlar scenario runner: Following Vehicle,
Since the CSV files are already exported so I dont know whether I miss any steps,
Could you please take a look, @ClemensLinnhoff 
Thank you

**Comment by ClemensLinnhoff** [comment]
When there is correct data in the CSV, there should also be correct data in the SensorData output.

How did you export/store the output OSI trace file? Are you using the [OpenMSL Trace File Writer](https://github.com/openMSL/sl-5-6-osi-trace-file-writer)? How are you converting the binary trace file to the readable trace you posted? Is it possible you mixed up SensorView and SensorData during the conversion?

**Comment by levanthanh3005** [comment]
Hi @ClemensLinnhoff, thank you,
I found out my issue,
when I got the osi, i forgot the tag: SensorData
```shell
python3.7 /OSIFormat/osi2read.py -d OutOfPerceptionModel.osi -o OutOfPerceptionModel.txth -t SensorData

```

Now it works,
Regards,
Thank you
Thanh
