### ISSUE TITLE
Tracking Coordinate Transformation not using mounting position

### ISSUE THREAD

**Issue by thomassedlmayer** [openMSL/sl-1-3-object-based-generic-perception-object-model#7]
I noticed that setting a mounting position not equal to (0,0,0) leads to detected objects being not correctly placed. I think, the issue lies in the tracking strategy.

The method 'calculate_dimension_and_position_from_pcl' performs the coordinate transformation function 'transform_position_from_object_to_ego_coordinates' (4 times btw; once in each switch/case) which does not consider the sensor mounting position. This would probably have to replaced with the function 'transform_position_from_object_to_sensor_coordinates'. Unfortunately, I can not make a PR because I don't have permissions to create branches on the repo, I think.

Feel free to check, if this issue is correctly fixed by my proposal.

**Comment by ClemensLinnhoff** [comment]
What exactly do you mean by 

> setting a mounting position not equal to (0,0,0) leads to detected objects being not correctly placed

?

The position of DetectedMovingObjects is set with respect to the coordinate system of the host vehicle (see [here](https://opensimulationinterface.github.io/open-simulation-interface/structosi3_1_1DetectedMovingObject.html#ad8a69c2327a7da76dba2d66dbcca54b6). So the sensor mounting position should not affect the position of the detected moving objects. If it does, this is indeed a bug and needs to be fixed.
But then the bug is probably in the data extraction strategy, as the vertices are transformed to the host vehicle coordinates there (and outputted as logical detections).

**Comment by thomassedlmayer** [comment]
Well, I guess OSI has some documentation issues... I always thought, all detected objects would be placed in the (virtual) sensor coordinate system. [Here](https://opensimulationinterface.github.io/osi-documentation/#_sensor_data) it is stated, that this is indeed the case. Though, as you said, the class reference documentation states that moving objects should be placed in the coordinate system of the sensor's vehicle frame. The images of stationary objects and traffic lights indicate that the middle of the rear axle may be the correct reference point. I am quite confused now that this is not documented well at all. I did not really pay too much attention to what is stated in the class reference documentation before. I always used the sensor mounting position as reference point.

**Comment by ClemensLinnhoff** [comment]
Yes this is quite confusing, I agree. But as I understand it, there is the virtual sensor coordinate system and the physical sensor coordinate system. The physical is the position where the actual physical sensor would be on the vehicle. The virtual can be anywhere on the vehicle e.g. in the middle of the rear axle.

So detected object are placed in the virtual sensor coordinate frame, but this is not at the position of the actual sensor, but e.g. on the rear axle.

**Comment by thomassedlmayer** [comment]
You are right, there are virtual and physical sensor mounting positions. And for detected moving objects the virtual position should be used. This is the one directly contained in the SensorData message. The physical sensor mounting position is only used for feature data and I guess it is the one contained in the [SensorDetectionHeader](https://opensimulationinterface.github.io/open-simulation-interface/structosi3_1_1SensorDetectionHeader.html)?

Though, in this sensor model no mounting position at all is considered for detected moving objects. Every moving object is placed in the ego vehicle's coordinate system (bounding box center if I remember correctly).

If I had to guess I would say that the official documentation is correct and the reference documentation is wrong but we should probably get some more opinions on that... I will create an issue in the OSI github repo showing the contradictions in the documentation.

**Comment by ClemensLinnhoff** [comment]
The detected objects from this model should be in vehicle coordinates (i.e. middle of rear axle), if the sensor mounting position (sensor_view_configuration.radar/lidar_sensor_view_configuration(0).mounting_position()) is defined accordingly. The coordinate transformation is performed [here](https://github.com/openMSL/sl-1-3-object-based-generic-perception-object-model/blob/main/src/model/strategies/data-extraction-strategy/src/DataExtractionStrategy.cpp#L211).

**Comment by thomassedlmayer** [comment]
Okay, so they are not supposed to be in sensor coordinates?

When I tried out the model the first time with filled SensorView::mounting_position, detected vehicles were shifted by exactly the defined mounting position compared to the respective ground truth objects. I tried to comprehend the code from back to front and then I found that in the Tracking strategy (calculate_dimension_and_position_from_pcl) some point cloud coordinates were only transformed into the ego vehicle coordinate system but not into the sensor coordinate system. I did not go any further and changed it to be transformed to sensor coordinates and it worked for me from then on...

Also, retracing the data flow costs a lot of time so I really didn't want to spend hours checking this. So I just thought, I'd give some quick response on my findings but if you think, this transformation in the tracking strategy is correct, I probably did something wrong somewhere.

Actually, I did not check or send any SensorViewConfiguration messages but I thought the model would probably just use the mounting position provided in the SensorView messages. Maybe that is the mismatch that explains my results?

**Comment by ClemensLinnhoff** [comment]
> Actually, I did not check or send any SensorViewConfiguration messages but I thought the model would probably just use the mounting position provided in the SensorView messages. Maybe that is the mismatch that explains my results?

That might explain the mismatch. I think the model uses the position set in its own parameterization profile.

But anyways, these coordinate transformations are quite error prone, so I would not eliminate the possibility, that there is something wrong in the model. Therefore, we are currently working on a test pipeline for OpenMSL and one of the first things will be to check the coordinate transformations.

**Comment by ClemensLinnhoff** [comment]
[Here](https://github.com/openMSL/sl-1-3-object-based-generic-perception-object-model/blob/main/src/model/strategies/tracking-strategy/src/Tracking.cpp#L350) the objects are transformed to ego coordinate system but it should be virtual sensor coordinate system. (There are also other places in the code with the same mistake.)
